### ISSUE TITLE
Where do i extract it? (Im on windows)

### ISSUE THREAD

**Issue by PowderedThe2nd** [magiczocker10/magiczockerOS#1]
idk where 2 extract

**Comment by magiczocker10** [comment]
If you download the data from GitHub via `Code > Download ZIP`, you need to extract the file to your computers root-directory.

Your computers root-directory should look like this:
`computer/<computer id>/startup`
`computer/<computer id>/magiczockerOS/...`

**Comment by PowderedThe2nd** [comment]
Where is the root dir?

**Comment by magiczocker10** [comment]
If you are using ComputerCraft through Minecraft, you can access it at `%appdata%\.minecraft\saves\<world-save-folder>\computers\<id>`.
But if you are using CraftOS-PC from MCJack123, you can find it at `%appdata%\CraftOS-PC\computer\<id>`.
